version: 2.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string
        default: ""
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version: ["2.6.6", "2.7.2", "3.0.0", "3.3.5"]
